export const skillTypes = ['tech-stack', 'libraries', 'tools'];

export const skills = [
  { type: 'tech-stack', label: 'Next.js' },
  { type: 'tech-stack', label: 'React.js' },
  { type: 'tech-stack', label: 'Typescript' },
  { type: 'tools', label: 'Git/Github' },
  { type: 'tech-stack', label: 'CSS' },
  { type: 'tech-stack', label: 'SCSS' },
  { type: 'tech-stack', label: 'GraphQL' },
  { type: 'tech-stack', label: 'REST API' },
  { type: 'tools', label: 'Figma' },
  { type: 'libraries', label: 'MaterialUI' },
  { type: 'libraries', label: 'Radix UI' },
  { type: 'libraries', label: 'Tailwind' },
  { type: 'libraries', label: 'Mantine' },
  { type: 'libraries', label: 'styled-components' },
  { type: 'libraries', label: 'Framer Motion' },
  { type: 'tools', label: 'Prisma' },
  { type: 'tools', label: 'Contentful' },
  { type: 'tools', label: 'Storybook' },
  { type: 'tools', label: 'Cypress' },
  { type: 'tools', label: 'Vercel' },
  { type: 'libraries', label: 'GSAP' },
  { type: 'libraries', label: 'SWR' },
  { type: 'libraries', label: 'zustand' },
  { type: 'tools', label: 'Netlify' },
  { type: 'tools', label: 'Webflow' },
  { type: 'tech-stack', label: 'Node.js' },
  { type: 'tech-stack', label: 'Python' },
  { type: 'tech-stack', label: 'Vue.js' },
  { type: 'tech-stack', label: 'Nuxt.js' },
  { type: 'tools', label: 'Prismic' },
];
